name: Engine Core DeKernalyxe

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2

    - name: Configuring MacOS Defined
      run: |
        source configure.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD" "$NGROK_AUTH_TOKEN"

    - name: ngrok is now listening to VNC connections on...
      run: |
        ngrok_url=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' || echo "Error: Unable to retrieve ngrok URL")
        echo "$ngrok_url"

    #- name: Downloading and Extracting IPSW 
      #run: |
        #source download.sh
        
    - name: Wait for 24 hours
      run: sleep 86400  # 24 hours in seconds
      
    - name: Ending Session
      run: echo "MacOs End MF"
