name: Engine Core

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2

      - name: Setting Up
        run: |
          source configure.sh

      - name: Downloading Packs
        run: |
          source index.sh

      - name: Ngrok and VNC Configuration
        run: |
          ngrok_url=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' || echo "Error: Unable to retrieve ngrok URL")
          echo "$ngrok_url"

      #- name: Setup tmate session
        #uses: mxschmitt/action-tmate@v2 #Tmate Session

      - name: Moving Components
        run: |
          sudo mkdir /Users/rhsalisu/Desktop/Firmware
          sudo mv /Users/runner/Desktop/* /Users/rhsalisu/Desktop/Firmware
          
      - name: Setting External Password
        run: |
          echo "Rabiu2004@" | sudo passwd root
          echo "Rabiu2004@" | sudo passwd runner

      - name: Holder
        run: sleep 86400  # 24 hours in seconds
